### ISSUE TITLE
Missing coffee-script dependency in readme

### ISSUE THREAD

**Issue by nstadigs** [roytruelove/angular-grunt-coffeescript#1]
"Ensure that you have node, npm, and grunt installed and in your path" <- should also include coffee-script

**Comment by roytruelove** [comment]
Coffeescript is included in package.json [here](https://github.com/roytruelove/angular-grunt-coffeescript/blob/master/package.json#L19), so it shouldn't need to be installed globally.  Please let me know if that doesn't work for your setup, I'll take a look.

**Comment by nstadigs** [comment]
It didn't work for me without installing coffeescript globally, because grunt is installed globally, and grunt can't read the grunt.coffee file without a global installation of coffeescript

**Comment by roytruelove** [comment]
Ah, you are correct, updated the readme.  Thanks!

**Comment by nstadigs** [comment]
Glad to help :)
